### ISSUE TITLE
Inline widgets

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10060]
The idea of having widgets in the timeline itself.

Checklist:
* [ ] Proof of concept
* [ ] MSC
* [ ] Implement alterations from MSC
* [ ] User-friendly design
* [ ] Out of labs

**Comment by turt2live** [comment]
I didn't post this earlier, apparently:

It looks like the timeouts are indeed not handled, assuming this is correct:
![image](https://user-images.githubusercontent.com/1190097/59738959-5c7fd100-9220-11e9-89aa-aabb4d610d90.png)

There's also several TODO comments in the area which may be of relevance. I suspect this project will turn into not just fixing the reported bugs, but also hardening the code paths.
