### ISSUE TITLE
Video / audio call stability

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11377]
We seem to have several issues with calls on different platforms / browsers lately. We should investigate each one to determine how to proceed:

* [x] [No sound during calls, unable to connect a call on Firefox · Issue #11366 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/11366#issuecomment-553337230)
* [ ] [Audio and Video call only work in the same LAN, no Debugging Information (e.g. TURN config) given · Issue #11368 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/11368)
* [ ] [Calls not supported Chrome · Issue #11348 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/11348)
* [x] [Cannot make calls with Catalina on Desktop · Issue #11151 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/11151)
* [ ] [1:1 voip just doesn't work on FF any more · Issue #11053 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/11053)

**Comment by dbkr** [comment]
Have fixed the identifiable issues here. Others I can't reproduce, so have asked for more info on the the relevant bugs and also in the #riot-web:matrix.org

It's possible that matrix.org being slow could have caused a lot of these issues (ie. the signalling taking so long to send that the call timed out).

**Comment by turt2live** [comment]
I'm counting this as fixed given the comments above.
