### ISSUE TITLE
Room list v2 feature implementation (outdated checklist)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13635]
The core algorithm being used is tracked as https://github.com/vector-im/riot-web/issues/11743 - this issue is all about the UI/UX features which need implementing. It's a bit long.

**This doesn't account for a huge number of features. See [the project board](https://github.com/vector-im/riot-web/projects/22) for more information on what is when.**

* [x] Expand/collapse lists
* [x] Resize list height
* [x] Badges on room tiles
  * [x] Shown on first render
  * [x] Update as the room updates (new messages, read messages, etc)
* [x] Hover effect on room tiles
  * [x] CSS
* [x] Hover effects on sublist
  * [x] Resize handle visible
  * [x] Show additional buttons on header
* [x] Per-list algorithm options
* [x] Add room button
* [x] Render room lists with tiles
* [ ] Render room lists lazily
* [x] Group/community invites
* [ ] Archive view
  * [ ] No historical section
  * [ ] Left panel takeover with "archive"
* [x] Filter box
  * [x] Filter by room name (partial)
  * [x] Filter by canonical alias (partial)
  * [x] Filter by alt alias (partial)
  * [x] <kbd>CTRL</kbd>+<kbd>K</kbd> to target
  * [x] <kbd>ESC</kbd> to clear
* [x] Community filter panel (LLP) support
* [ ] Custom tag support
* [x] Context menu show
  * [x] Leave room
  * [x] Tag (favourite, DM, low prio, off)
  * [x] Room settings
* [x] Accessibility - TODO: Improve list of features we intentionally support
  * [x] Natural tab ordering/stops
  * [x] Arrow key navigation
  * [x] `aria-label`s and `aria-level`s
  * [x] <kbd>ALT</kbd>+<kbd>UP</kbd>/<kbd>DOWN</kbd> navigability
  * [x] Automatic scrolling when using keyboard
  * [x] <kbd>Enter</kbd> to view room
  * [x] <kbd>LEFT</kbd>/<kbd>RIGHT</kbd> to collapse/expand sublist
  * [x] Other TODO comments
* [ ] Room tile error boundary
* [x] Incoming call support
* [x] Jitsi support
* [x] Presence decoration
* [x] Globe decoration
* [x] Update room tiles when room decorations change (name, join rules, e2e, etc)
* [x] Breadcrumbs update with viewed rooms
* [ ] Custom theme support
* [ ] Upload file animation
* [ ] Upload failed icon
* [ ] Typing animation
* [ ] Breadcrumbs
  * [x] View
  * [ ] Become smaller on scroll
* [ ] Missed notifications bar (when scrolled)
* [x] Minimized view
* [x] Home link on user menu

Algorithmic behaviour:
* [x] Sticky room behaves as documented (stay in place)
* [x] Importance algorithm
  * [x] List sorting algorithm applied to *category lists* (recents vs alphabetical)
  * [x] Red > Grey > Bold > Idle
* [x] Natural algorithm
  * [x] List sorting applied to *sublists* (recents vs alphabetical)
* [ ] Update behaviour/regenerate lists when options change
  * [ ] Custom tags
  * [x] Importance vs Natural ordering
  * [x] List sorting algorithm (skip regeneration for whole list?)

Tests (end-to-end as well as unit/integration tests):
* [ ] Importance algorithm behaviour (end-to-end and integration)
* [ ] Natural algorithm behaviour (end-to-end and integration)
* ... and whatever else is possible (probably for each individual feature listed above)

**Comment by ingingin** [comment]
#13701

**Comment by turt2live** [comment]
Extremely early and unapproved designs show we might be interested in having an option to order favourites like regular rooms, so https://github.com/matrix-org/matrix-doc/pull/2579 exists (it was about time anyways). This would include https://github.com/vector-im/riot-web/issues/4484

**Comment by turt2live** [comment]
Finally closing this and it's 2mb screenshots' worth of referenced PRs. Everything else is tracked in the `new-room-list` label.
