### ISSUE TITLE
Chat text autocomplete (design only): needs design completion 

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1761]
Chat text autocomplete (design only): needs more design work as per comments and feedback

**Comment by ara4n** [comment]
Only the design is needed here - implementing this is on @aviraldg's radar (the implementation already exists; he'll just need to update the look & feel to match the final design).

Just to record yesterday's proposal, the idea is:

* Status bar is hidden by default.  It appears only for:
  * Error messages (e.g. the "connectivity failure" warning)
  * "You have N unread messages" (when scrolled up the page)
  * "Matthew and 5 others are typing" (but *only* when scrolled up the page)
* Typing notifications are shown like the iMessage ellipsis chat bubble, as a phantom inline message in the timeline.  To stop the timeline bouncing up and down as people start and stop typing, we debounce the timeline animation - after making room for the typing notification by scrolling up, the timeline waits N seconds (if at all?) to scroll back down again.

Making the new status bar behaviour work properly will be Hard, as the scroll logic in RoomView, MessagePanel, TimelinePanel etc is surprisingly complicated - this must be done by the Vector core team.

On autocomplete UI itself:

* Press tab to bring up the autocomplete UI at any point.  It tries to autocomplete the thing you're typing (if any), if not gives a selection of all the terms you could autocomplete.
* Options are arranged into sections: slash-commands, emoji, room aliases, room IDs etc.
* User hits tab and shift-tab to cycle through the options (as a raster scan: left-to-right and then wrapping to the next row when hitting the end).
* User can hit up & down cursor keys to skip between the rows to navigate the 'grid'.
* User can also trigger the autocomplete UI by starting to type something known to trigger it - : for emoji, @ for username, # for room alias, / for command.

@aviraldg - i think this ^ is what we'd basically converged on already, and I assume that adjusting the current labs implementation to match is on your radar.  The final design is in progress, but looks very similar indeed to what you've already built :)

**Comment by bradlegge** [comment]
Screen URL:

https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=57838023cba01af440b28692

**Comment by ara4n** [comment]
See also https://github.com/vector-im/vector-web/issues/1153

**Comment by antikewl** [comment]
Aviral's current implentation, for reference: 
<img width="674" alt="screen shot 2016-08-12 at 09 40 19" src="https://cloud.githubusercontent.com/assets/3658981/17617223/d94433be-6070-11e6-9317-06e773d0aab2.png">

**Comment by ara4n** [comment]
You can also get at this on vector.im/develop by flipping the 'Rich Text 
Editor' labs button in Settings.  The UI/UX there is entirely 
placeholder, needless to say.

**Comment by antikewl** [comment]
Ben posted these to the vector design chat last week, but adding them here too for review.

zpl.io/1LOFp2
zpl.io/ZqX6TS

**Comment by jansol** [comment]
Some additions from my other issue about this:

* If the completion dialog appears automatically, it should not touch the input and not activate any completion list entry until the user presses tab or an arrow to navigate it. Selecting an entry should insert it immediately but keep the dialog open for cycling through completions.
* Continuing typing should append to a completion if one has been done.
* Many people expect enter to accept a completion. Maybe do that, insert a space and close the completion dialog in this case?

**Comment by ara4n** [comment]
Agreed with @jansol, with the following provisos:
 * only tab should trigger shifting into autocompletion mode (i.e. actually using the autocomplete UI).  Arrow keys are otherwise for navigating history, moving the  or editing (in future).  
 * i'm not sure that enter/return is necessary to accept an autocompletion.  The act of pressing tab/shift-tab/cursor-keys should (temporarily) replace the current contents in the MessageComposer, so you shouldn't need the additional keypress, which could be preserved for actually sending messages.

**Comment by aviraldg** [comment]
Tacking on what @ara4n said on #vector:matrix.org:

The idea is that autocomplete popups can be entirely ignored by the user whilst typing unless they actually want to make use of them.
The autocomplete grid UI appears after a delay if the user pauses mid-word, and there are possible autocompletion results for completing the current word.
This delay could be shorter if the last character typed is an autocomplete-trigger - one of :, @, #, /)
The UI does nothing unless the user clicks on one of the proposals, or hits tab to enter autocompleting mode.
In autocompleting mode:
pressing tab replaces the current partial word in the message composer with an autocompletion result (e.g. a user object, room object, emoji, /command).
pressing arrow keys navigates the options presented in the autocomplete grid UI. left and right arrows are equivalent to tab & shift-tab.
Hitting escape cancels autocomplete mode, returning the messagecomposer to the state before autocompletion mode was entered.
Hitting tab or shift-tab cycles forwards/backwards through the list of results (of all available types).
The available types vary based on the sigil of the term being completed:
If the completion term has no sigil, we should search users and then rooms.
If the completion term has a @ sigil, we should search only users (both by displayname and by user id)
If the completion term has a # sigil, we should search only rooms (both by room name and by room alias)
If the completion term has a / sigil, we should search only slash commands
If the completion term has a : sigil, we should search only emoji.
:) and :/ etc could be added as special case emoji shortcuts for :smiley_face: etc.
There is no need to ever hit 'return' or 'enter' to accept a result, given possible results are already provisionally accepted in the composer during navigation.

**Comment by wmwragg** [comment]
As it is now being implemented, I am assuming this design only ticket is complete

**Comment by ara4n** [comment]
reopening to turn this into an implementation ticket for @aviraldg

**Comment by ara4n** [comment]
I've split out the Status Bar bits of this into a new ticket (#1991)

**Comment by aviraldg** [comment]
@ara4n I'd say the design here has been sufficiently implemented with the remaining work mainly being bug fixing?

**Comment by ara4n** [comment]
Whilst the autocomplete stuff is merged, there is a bunch of polish & bugfixing required.  As discussed on #riot-dev with @aviraldg : rather than, filing a million little tickets, going to track the remaining work needed before we merge here as tickyboxes.

* [ ] autocompleting displaynames which include disambiguated mxids in RTE results in spurious lozenges #2231
* [ ] Wrap/ellipsize autocomplete text correctly #2230
* [ ] Speed up autocomplete matching #1976.  At the least, please let's just turn off fuzzy matching for now.  It can be added back in again when performant.  Fuzzy matching is not a merge blocker.
* [ ] Autocomplete should order based on who was last speaking #98 (Which was working pre-RTE)
* [ ] press t<tab><tab><tab> - tabcomplete through room aliases like #test:matrix.org - cool! hit escape to hide the tabcompletion UI - reverts - cool! start hitting tab again... autocomplete UI doesn't display :(
 * [ ] press aviral<tab> - correctly tab completes to "aviraldg: ". keep typing, but the autocompletion UI remains present, trying to autocomplete the next things you say even though they don't look like rooms, names, emoji, etc. (related to #2189?) - this one is incredibly annoying.
 * [ ] Tab complete on a room alias should probably append a space, similar to what we do for users.
 * [ ] Selecting the input (e.g. by ctrl or cmd-A) adds a bunch of additional autocompletion options to the list if it's open, which is quite disconcerting.  (e.g. aviral<tab><ctrl-A> -> what?).  We should autocomplete options purely based on the stem that the cursor is currently at the end of, rather than looking inside the selection range, if any
 * [ ] Pause before displaying the autocomplete dialog.  It's completely unnecessary to display it the second someone presses @ or # or :.  Instead there should be a pause of 250ms or so before the autocomplete UI appears, otherwise it's just distracting and slows things down when typing .
 * [ ] In retrospect, I think we should Interpret `letter<tab>` autocomplete as searching displaynames/usernames only; not room names.  If you want to refer to a room by linkable name, you will always start with #.  Whereas our convention is to autocomplete plain fragments (i.e. no sigil) as people.  E.g. the chances of me wanting to refer to #aviralrocks:matrix.org when I type `av<tab>` rather than just trying to autocomplete the name Aviral is negligible.

And two nice-to-have:
 * [ ] Still no :( :) style shortcuts for `:smile:` style emoji (but isn't a blocker)
 * [ ] Not having an emoji grid is an oversight (but isn't a blocker)

In general, it's feeling incredibly good though - *so* close...

**Comment by turt2live** [comment]
*I'm not sure this is the right ticket, but to avoid opening another ticket, here we go.*

There's a couple oddities in the current rendition of the composer. Not sure if they've been fixed in a PR somewhere (I don't have a nice way to test it), but for documentation's sake:

* [ ] Pasting multiline text between triple backticks causes the composer to not highlight correctly
  ![image](https://cloud.githubusercontent.com/assets/1190097/23310870/470ca5a8-fa71-11e6-8647-7fcf5a77e704.png)
  1. Type 3 backticks
  2. **Paste** multiple lines of text
  3. Close the backticks
  4. Note that the block doesn't format itself
  This is a non-issue when composing the multiple lines yourself (ie: 3 backticks, type, shift+enter, type, backticks). This is also a non-issue when the text you're pasting is 1 line (ie: no linefeed). 
* [ ] Autocompleting `/kick` and `/ban` aren't friendly at all
  1. Start the autocomplete process, like so:
      ![image](https://cloud.githubusercontent.com/assets/1190097/23311001/be1eaa42-fa71-11e6-86d5-3fd3dd7858e3.png)
  2. Approve the suggestion
  3. Note that the inserted text won't help you kick/ban that user
      ![image](https://cloud.githubusercontent.com/assets/1190097/23311037/e0f91f2a-fa71-11e6-82d4-4f198eac54e6.png)

**Comment by aviraldg** [comment]
@turt2live Couple of points:
1. I would actually prefer separate issues, since batching everything up makes slows down the rate at which features/fixes can be released.
2. Highlighting has been disabled on the upcoming RTE fixes PR, since it's based on a hacky regexp.
3. I would not create a separate issue for `/kick` / `/ban` completions as those should start working once we do user entities with embedded mxids (something I plan to work on as soon as `rte-fixes` is merged)
4. Like I said, the markdown highlighting feature has been disabled.

**Comment by grahamperrin** [comment]
Is a review of this issue timely? Just a though.

**Comment by lukebarnard1** [comment]
I think the majority of things discussed in this issue are either covered in other issues or out of date, so I'm going to close this.
