### ISSUE TITLE
Communities (aka sub-rooms or room categories)

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2454]
Slightly different to tags, though they need to interact somehow. Some sort of cross-user metadata on rooms, which the client then uses to categorise rooms in the room list.

**Comment by richvdh** [comment]
Per https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1476215287707JLfoF:chat.cryptochat.io: 

> We expect to be adding many different Crypto Currency rooms. Many of them will have similar room needs. So, both Coin '123' and Coin '456' may want a 'Welcome' room, 'Support' room, 'Marketing' and a 'Trading' room. We are trying to avoid having the following under the 'Rooms' section in the left for people that have joined each of them:
> 
> #Coin123_Welcome:chat.cryptochat.io
> #Coin123_Support:chat.cryptochat.io
> #Coin123_Marketing:chat.cryptochat.io
> #Coin123_Trading:chat.cryptochat.io
> #Coin456_Welcome:chat.cryptochat.io
> #Coin456_Support:chat.cryptochat.io
> #Coin456_Marketing:chat.cryptochat.io
> #Coin456_Trading:chat.cryptochat.io

**Comment by ara4n** [comment]
I could have sworn we had a bug for this already, given the number of people who've asked for slack-style subrooms. but apparently not. agreed that it would be very useful.

**Comment by richvdh** [comment]
I don't think sub-rooms were quite what was asked for, but they do sound like another valid way of solving the problem

**Comment by sbts** [comment]
I'll jump on this bandwagon :-)

perhaps the mechanism could be based on the room name instead of special tags. It's a really common mechanism to use underscores (as shown in the above example) to nest catagories in roomnames on IRC etc, in fact I've done it myself here for #ledgersmb and some sub rooms

perhaps the only "config" we need is a room flag saying that it's part of a room group, then the underscores can delimit the "levels"

**Comment by edykstra** [comment]
I think Riot/Matrix is already destined to be a 'Slack killer', but this would pretty much clinch it. Especially if a user can join see all the rooms in a Category at the same time. If the Room Directory has a Category filter too, and then the user can easily join them as desired.

**Comment by sbts** [comment]
Thinking about this further from an implementation perspective, possibly the most flexible method would be to have an optional room setting of "parent room", and an optional per user setting setting hash "room parents" containing "room_name=parent_room_name" pairs

Any UI can then (possibly configurably) either honour or ignore these keys to modify the way rooms are displayed

**Comment by ara4n** [comment]
This is quite related to #1373. I suggest we consider solving both at the same time.

**Comment by AndrewJDR** [comment]
Just had to stop by and say how sorely needed this is! Especially using a bridge that does some level of user puppetting, the room listing has become *very* disorganized.

**Comment by ara4n** [comment]
This keeps coming up more and more - especially from Discord users, who are used to having multiple groups of rooms (which discord calls 'servers' confusingly), thus grouping together related sets of rooms for a given community, similarly to Slack's teams.

https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1491607246420851NlHhu:matrix.org has some additional thoughts on it, which can be summarised as:

* We should support defining groups of rooms in the directory somehow
* We should support grouping together rooms in the RoomList, possibly just having them as a RoomSubList.
* We would need some kind of navigation to easily discover other rooms in this group from the room list - perhaps pre-adding them to the roomlist (albeit not joining them) - this is effectively #3266

**Comment by jimscarver** [comment]
I am facing this issue in two communities.  What is the best way to set up a list of rooms corresponding to slack channels?

**Comment by jansol** [comment]
Given the Discord users, maybe calling these groups "Communities" would be more descriptive?

**Comment by ara4n** [comment]
way ahead of you ;)
<img width="351" alt="screen shot 2017-05-07 at 22 48 50" src="https://cloud.githubusercontent.com/assets/1294269/25785407/60c9c540-3377-11e7-9c7d-2775154a7761.png">
@AmandineLP & I are currently arguing semantics and then put out a proposal here; agreed this is critical.

**Comment by ara4n** [comment]
n.b. these are different to [custom room tags](https://github.com/vector-im/riot-web/issues/1373), which are strictly per-user (but may perhaps contribute to defining communities), and also Matrix Groups (#3842), which are effectively an ACL construct to define sets of users.

**Comment by ara4n** [comment]
I've deliberately split the concept of having room hierarchies out of this into #3843 (unless of course Communities end up being some kind of ungodly usenet #comp.internet.services:matrix.org style global taxonomy ;D)

**Comment by gagarine** [comment]
Communities need some kind of ACL. In my use case we want to use riot instead of slack for a university associations. We want members to joint "the community" on riot and then have access to some room but not all. Giving access to members of the community of those "secret" room should be easy.

Also if you joined different community, you should be able to mute everything from one community so you can concentrate on the one you actually working.

This features is really what make slack interesting for team.

**Comment by z3ntu** [comment]
Communities are now available in the Riot client.

**Comment by ara4n** [comment]
Major items still remaining here (given this is effectively the master bug for communities) are:
 * [ ] Groups on mobile
 * [ ] Editing admins in a group
 * [ ] Exposing flair for bridged networks

**Comment by stuartpb** [comment]
> Warning: any person you add to a community will be publicly visible to anyone who knows the community ID

What would it take to make a community where membership is only visible to other members who have been invited?

**Comment by richvdh** [comment]
> Editing admins in a group

This seems to be covered by #5240, so I guess this is done.

**Comment by LexiconCode** [comment]
I feel the communities are more representative of groups related chat rooms that might have sub rooms of their own individually. As how it's currently implemented it's just a collection of chat rooms.
