### ISSUE TITLE
Finish LeftLeftPanel (a.k.a LLP a.k.a TagPanel)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5830]
This is a tracker bug to track implementing the "second strawman design" from https://docs.google.com/document/d/1eSKqH9NuYC2aBt8fOWQuICS84KfL2eNlIWRoV5DinoI

The main points are:
 * [x] Implement basic LeftLeftPanel
 * [x] Shift and Ctrl/Cmd click to select groups
 * [x] Drop & Drag to reorder the groups
 * [x] Switch the (+) button for the (groups) button - see details below. (https://github.com/matrix-org/matrix-react-sdk/pull/1744, https://github.com/vector-im/riot-web/pull/6130)
* [x] Context menu on LLP icons to let you view the group in question (https://github.com/matrix-org/matrix-react-sdk/pull/1743, https://github.com/vector-im/riot-web/pull/6127)
 * [x] Drop & Drag from GroupsPage to add groups from rooms to it (https://github.com/vector-im/riot-web/pull/6143, https://github.com/matrix-org/matrix-react-sdk/pull/1751)
 * [x] Global selection icon at top of list (https://matrix.to/#/#riot-design:lant.uk/$1518693142178UAIhR:lant.uk - https://github.com/matrix-org/matrix-react-sdk/pull/1759, https://github.com/vector-im/riot-web/pull/6187)
 * [x] Microcopy for dragging group avatars to TagPanel: https://github.com/matrix-org/matrix-react-sdk/pull/1777

Secondary points are:
 - [x] Ability to scroll the list (https://github.com/vector-im/riot-web/issues/5738) (PRs: matrix-org/matrix-react-sdk#1759, #6187)
 - Ability to tag and untag rooms to be associated with the group (if appropriate)
 - Show badges for unread messages within a given group?
 - Animated GIF for moving GroupTile avatars (blocked on @ara4n)

**Comment by ara4n** [comment]
So, huge discussion about how to resolve the remaining LLP points.

 * Context menu:
  * (...) in the top right of the icon, like we do on the collapsed LeftPanel today
  * options are:
    * View community
    * Remove
 * (Drag icons off the LLP to remove them.) <-- hard to do nicely with react-beautiful-dnd so perhaps skip it at first
 * Remove the dedicated (+) create button, as creation is unusual
 * Move the (communities) button from the BottomLeftMenu to the BottomLeftLeftPanel
 * Support DnD from the GroupsPage to the LLP in order to add groups onto it
   * Microcopy on the GroupsPage to tell people to do this
   * Put the groups on plinths to make them look more draggable and use `cursor: drag` or whatever rather than `cursor: point`
 * ...for now, we skip DnD of rooms into groups in order to apply the tag overlay, because we think that it might be good enough to just be able to nicely tweak the list of groups present on the LLP, and we'll see if we need to tweak the group membership further still later on. Plus we can already create private groups which help with this anyway!

**Comment by turt2live** [comment]
> Move the (communities) button from the BottomLeftMenu to the BottomLeftLeftPanel

Any reason for not making use of the void at the top of the panel? or is that where the 'global' button is going?

**Comment by ara4n** [comment]
the latter
