### ISSUE TITLE
Many buttons are very hard to find.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5831]
Expanding this out from the https://github.com/vector-im/riot-web/issues/2984 'General UX Thread' bug:

 * [ ] Empirically, folks find the invite button hard to find on the bottom-right. Move it to below the filter on the top right?
 * [ ] Nobody can find the NotifPanel or FilePanel buttons.  This can be helped by putting badges on them when they have something of interest
 * [ ] The 'new room' and 'new chat' buttons seem to get lost.
 * [x] We could move the 'groups' button into the LLP

**Comment by turt2live** [comment]
as claimed by Matthew, I'm inclined to agree
