### ISSUE TITLE
[Tracking-Issue for a PR] Update electron-builder

### ISSUE THREAD

**Issue by MTRNord** [vector-im/riot-web#6649]
electron-builder is really old. ~~As @t3chguy pointed out nsis is the reason as it did a uninstall and reinstall on every update.~~
~~This seems to have changed since `electron-builder 19.28.4` and `electron-updater 2.9.3` (See https://github.com/electron-userland/electron-builder/commit/f6fe96ff08e9f2d57e645c5c6e89d0d628530f9a and https://github.com/electron-userland/electron-builder/issues/1523)~~

~~Also migrating might be a issue but that seems to be solved too using https://github.com/electron-userland/electron-builder/issues/837#issuecomment-355698368 . On Mac it apparently uses squirrel still so no need to migrate anything over there.~~

I will if I have enough time Update and try this and after it open a PR.

Things to be done and to be tested:

- [ ] Update electron-builder
- [ ] Update electron-updater
- [ ] Update the update Code to match the new updater
- [ ] Find out changes needed to be done at the Update server
- [ ] Check if 32 and 64 bit installer get generated (not bundled but seperated)
~~- [ ] Test updates on Windows from Squirrel to Nsis~~
~~- [ ] Test updates on Windows from Nsis to Nsis~~
- [ ] Test updates
- [ ] Test updates on MacOS (needs help as I dont have a Mac)
- [ ] Test .deb generating

**Comment by MTRNord** [comment]
Apparently they do still support squirrel and I just missed it. To use it it requires this plugin: https://www.npmjs.com/package/electron-builder-squirrel-windows

**Comment by t3chguy** [comment]
We now use a fairly recent version of electron-builder

**Comment by jryans** [comment]
Yes, we update this regularly as part of releases. I don't think we need this tracking issue.
