### ISSUE TITLE
Redesign: Authentication Flow Meta

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7586]
### In Scope

- [x] [Redesign: Add a form field component](https://github.com/matrix-org/matrix-react-sdk/pull/2463) 
- [x] [Redesign: Form field tweaks](https://github.com/matrix-org/matrix-react-sdk/pull/2468)
- [x] [Redesign: Add modal look to authentication flows](https://github.com/vector-im/riot-web/issues/8223)
- [x] [Login screen doesn't adapt well to viewport that isn't high enough](https://github.com/vector-im/riot-web/issues/8284)
- [x] [Redesign: Style login to match design](https://github.com/vector-im/riot-web/issues/8167)
- [x] [Redesign: Style registration to match design](https://github.com/vector-im/riot-web/issues/8168)
- [x] [Redesign: Route ILAG to regular authentication](https://github.com/vector-im/riot-web/issues/8222)
- [x] [Make auth validation smoother and less annoying](https://github.com/vector-im/riot-web/issues/8293)
- [x] [.well-known login bug (new login)](https://github.com/vector-im/riot-web/issues/8346)
- [x] [If HS registration is disabled, errors trying to register are awful](https://github.com/vector-im/riot-web/issues/8334)
- [x] [Make registration fields respond to available registration flows from the HS](https://github.com/vector-im/riot-web/issues/8219)
- [x] [Redesign: Onboarding: Full screen background image](https://github.com/vector-im/riot-web/issues/8163)
- [x] ["disable_custom_urls" prevent account registration](https://github.com/vector-im/riot-web/issues/8405)
- [x] [Rework login to match design v2](https://github.com/vector-im/riot-web/issues/8345)
- [x] [Redesign: Style reset password to match design](https://github.com/vector-im/riot-web/issues/8169)
- [x] [Add configurable welcome page, move content of home to it](https://github.com/vector-im/riot-web/issues/8422)
- [x] [credit @octete for the auth page bg (CC-BY-SA)](https://github.com/vector-im/riot-web/issues/8374)
- [x] [Detect Modular via config.json](https://github.com/vector-im/riot-web/issues/8253)
- [x] [Having a default_hs_url shouldn't leave you at the server picker](https://github.com/vector-im/riot-web/issues/8840)
- [x] [Allowed characters error on registration is unhelpful](https://github.com/vector-im/riot-web/issues/8839)
- [x] [We should have a default_server_name config.json property that defaults homeserver url and identity server url via .well-known](https://github.com/vector-im/riot-web/issues/8763)
- [x] [Change "Edit" link in registration to "Change"](https://github.com/vector-im/riot-web/issues/8853)
- [x] [Registration on riot.im/develop defaults to Matrix with empty screen](https://github.com/vector-im/riot-web/issues/8862)
- [x] ['Passwords don't match' doesn't disappear even when they match](https://github.com/vector-im/riot-web/issues/8769)
- [x] [After setting a custom HS in sign-in, going to create account reverts it to matrix.org](https://github.com/vector-im/riot-web/issues/8695)
- [x] [Registration spinner doesn't fit in the box](https://github.com/vector-im/riot-web/issues/8661)
- [x] [Can't use a password manager to register an account](https://github.com/vector-im/riot-web/issues/7868)
- [x] [Authentication: Use new Field component](https://github.com/vector-im/riot-web/issues/8262)
- [ ] [Redesign: Input validation for registration](https://github.com/vector-im/riot-web/issues/8170)
- [ ] [Redesign: Input validation for login](https://github.com/vector-im/riot-web/issues/8292)
- [ ] [Registration doesn't show a spinner between submitting the registration form and loading the CAPTCHA](https://github.com/vector-im/riot-web/issues/8349)
- [ ] [Add server name as contextual label to username input ](https://github.com/vector-im/riot-web/issues/8295)
- [ ] [Redesign: Place auth "Next" button on same row as links to alternate screens](https://github.com/vector-im/riot-web/issues/8266)
- [ ] [Extract auth components for Modular up to riot-web](https://github.com/vector-im/riot-web/issues/8297)
- [ ] [Registration should also do .well-known discovery](https://github.com/vector-im/riot-web/issues/8309)
- [ ] [Add server name input using .well-known for custom servers](https://github.com/vector-im/riot-web/issues/8310)
- [ ] [Auth: Make it feel like it's really submitting](https://github.com/vector-im/riot-web/issues/8417)
- [ ] [Unify homeserver URL error messages across auth screens](https://github.com/vector-im/riot-web/issues/8429)
- [ ] [Add option to remove confusing warning when using disable_custom_urls: true on login error](https://github.com/vector-im/riot-web/issues/8848)
- [ ] [Add additional modes to configure what's allowed during login / registration](https://github.com/vector-im/riot-web/issues/8824)
- [x] [Country picker in phone number registration is DARK THEME when everything else isn't](https://github.com/vector-im/riot-web/issues/8990)

---

### Deferred

- [Authentication: Add public server search box](https://github.com/vector-im/riot-web/issues/8273)
- [Change to a single username / email / phone input for login](https://github.com/vector-im/riot-web/issues/8311)
- [Server URL resets when changing language on login](https://github.com/vector-im/riot-web/issues/8741)
- [Authentication visual nits](https://github.com/vector-im/riot-web/issues/8325)

**Comment by bwindels** [comment]
After talking to Nad, this seems risky in that we would need to have design for the whole registration flow when starting on this, which is completely missing now and might take a while. So postponing this for now.

**Comment by jryans** [comment]
I have converted this to a meta issue for login / registration / onboarding issues, with a tracking list at the top of the issue.

**Comment by jryans** [comment]
I'll remove this meta from the project board and just track each piece instead.

**Comment by jryans** [comment]
We now have a `feature:authentication` label for this project, so I don't think we need this meta issue anymore.
