### ISSUE TITLE
Redesign: User Settings

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7605]
* [x] https://github.com/vector-im/riot-web/issues/8199 | Redesign: Modalize and mock tabs for user settings
* [x] https://github.com/vector-im/riot-web/issues/8200 | Redesign: General tab of user settings
* [x] https://github.com/vector-im/riot-web/issues/8201 | Redesign: Notifications tab of user settings
* [x] https://github.com/vector-im/riot-web/issues/8202 | Redesign: Preferences tab of user settings
* [x] https://github.com/vector-im/riot-web/issues/8203 | Redesign: Voice & Video tab of user settings
* [x] https://github.com/vector-im/riot-web/issues/8204 | Redesign: Security & Privacy tab of user settings
* [x] https://github.com/vector-im/riot-web/issues/8205 | Redesign: Labs tab of user settings
* [x] https://github.com/vector-im/riot-web/issues/8206 | Redesign: Help & About tab of user settings

**Comment by turt2live** [comment]
I've converted the original issue to be a collection of smaller issues to better track progress.

**Comment by turt2live** [comment]
The core of this is done. All that's left is tidying it up: https://github.com/vector-im/riot-web/issues/8207

**Comment by Wambong** [comment]
i am trying to redesign element web client registration page to add a displayname in the input fields
