### ISSUE TITLE
Redesign: Room Settings

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7606]
* [x] https://github.com/vector-im/riot-web/issues/8254 | Redesign: Modalize and mock tabs for room settings
* [x] https://github.com/vector-im/riot-web/issues/8255 | Redesign: General tab of room settings
* [x] https://github.com/vector-im/riot-web/issues/8256 | Redesign: Security & Privacy tab of room settings
* [x] https://github.com/vector-im/riot-web/issues/8257 | Redesign: Roles & Permissions tab of room settings
* [x] https://github.com/vector-im/riot-web/issues/8258 | Redesign: Advanced tab of room settings

**Comment by cwmke** [comment]
After opening room settings by clicking the room name, I kept clicking on the clear avatar button thinking it was the close room button. I thought it wasn't working until I noticed the X on the far right next to save and then hovered on the clear avatar button.

![screenshot from 2018-12-25 10-36-25](https://user-images.githubusercontent.com/1923967/50424865-470d8980-0831-11e9-97c0-f8dc8091412a.png)

**Comment by turt2live** [comment]
This issue is the issue for implementing the new design for the settings. It'll be fixed in due time, and all the weird bugs with it.

**Comment by turt2live** [comment]
I've broken the top comment out into individual tasks to make tracking a bit easier.

**Comment by turt2live** [comment]
This is now complete. The remainder of the work (ie: polish) is being tracked at https://github.com/vector-im/riot-web/issues/8207
