### ISSUE TITLE
Canonical issue for captcha not working on desktop

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8288]
The captcha thing doesn't work on desktop due to cross-origin badness (I believe). This lead us to have a "please use a web browser" prompt instead. Recently, that prompt stopped showing up. Additionally, we have some history for these kinds of issues:

* [ ] https://github.com/vector-im/riot-web/issues/8287 - The web browser prompt doesn't work
* [ ] https://github.com/vector-im/riot-web/issues/4893 - Captcha shows up wrong
* [ ] https://github.com/vector-im/riot-web/issues/7617 - Cannot escape captcha 

We should probably be using the fallback API here or at least providing the user with an escape route. Also, the prompt should work all the time.

*Note to toml: feel free to close/reopen/whatever the other issues I've referenced. It's in your hands now.*

**Comment by aaronraimist** [comment]
One solution may be to switch to a different CAPTCHA provider: #3606

**Comment by jryans** [comment]
It looks like captchas now work in Riot desktop, so I have [made a change](https://github.com/matrix-org/matrix-react-sdk/pull/2663) to allow them there. Hopefully that will continue to be true in production usage on all OSes.
