### ISSUE TITLE
Meta: Reliable Storage

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9220]
## Summary

Our storage subsystems can fail out from under us, leading to various kinds of confused application state. This meta issue tracks a set of improvements to move towards something more reliable.

## Investigation

See the [investigation notes](https://github.com/matrix-org/matrix-js-sdk/blob/develop/docs/storage-notes.md) for more detail on how browsers behave today.

## Planned Improvements

- [x] [Add console logging to record storage state](https://github.com/vector-im/riot-web/issues/9271)
- [x] [Send telemetry about storage consistency](https://github.com/vector-im/riot-web/issues/9272)
- [x] [Improve detection of fallback stores](https://github.com/vector-im/riot-web/issues/9309)
- [x] [Detect case of IndexedDB being deleted and alert user to sign out](https://github.com/vector-im/riot-web/issues/9109)
- [x] [Investigate persistent storage for Electron where we'd like it to default on](https://github.com/vector-im/riot-web/issues/9338)

## Deferred Improvements

* [Detect case of Firefox profile storage corruption](https://github.com/vector-im/riot-web/issues/7465)
* [Consider storage estimation to predict issue coming up](https://github.com/vector-im/riot-web/issues/9361)
* [Consider switching to persistent storage to avoid this issue](https://github.com/vector-im/riot-web/issues/9362)
* [Move user's own Olm keys to localStorage, so that they can recover when IndexedDB disappears](https://matrix.to/#/!RbKRuLTvHIhArQcvjr:matrix.org/$1553091062267114tiefP:matrix.org?via=matrix.org&via=lant.uk&via=t2l.io)
* Move more logic inside `StorageManager`
* Check that IDB stores are the expected version and all object stores are actually created (see also https://github.com/vector-im/riot-web/issues/8759)
* Add debug panel in Settings to investigate storage state
* Telemetry attached to UISIs / UTDs (visitor logs with storage state seem good enough for now)

**Comment by jryans** [comment]
All of improvements we planned to tackle now have been completed. The remaining related items are linked above in the deferred section. I think we can close this issue and use the remaining independent issues going forward.
